name: dart_sandbox_02102025
description: This is a sandbox.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.8

dependencies:
  # path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
